swagger: '2.0'
info:
  description: 'This a simple api documintation, build with love by Fawzi E. Abdulfattah'
  version: 1.0.0
  title: Online Hospital
  contact:
    email: iifawzie@gmail.com
host: www.google.com
basePath: /api

tags:
  - name: Auth
    description: Everything related to Authentican

paths:

  /signup:

    post:
      tags:
        - Auth
      summary: The user which will be stored in the `Users` table
      description: ''
      consumes:
        - application/json
      produces:
        - application/json
      parameters:

        - in: body
          name: body
          description: The User Data which will be stored in the `Users` table
          required: true
          schema: 
             $ref: '#/definitions/signup'

      responses:
        '201':
          description: 201 (Created)
          schema:
            $ref: '#/definitions/ApiResponse'

definitions:

  signup:
    type: object
    properties:
      id:
        type: integer
        format: int64
      username:
        type: string
      email:
        type: string
      password:
        type: string
      phone:
        type: string
      userStatus:
        type: integer
        format: int32
        description: User Status

  ApiResponse:
    type: object
    properties:
      status:
        type: boolean
      message:
        type: string
