require("../utils/db");
const { users } = require("../models/users");
const { admins } = require("../models/admins");
const { categories } = require("../models/categories");
const { certifications } = require("../models/certifications");
const {doctors} = require("../models/doctors");
const {slots} = require("../models/slots");
const {appointments} = require("../models/appointments");
const {prescriptions} = require("../models/prescriptions");
const {messages} = require("../models/messages");
const {rates} = require("../models/rates");
const systemUser = require("../utils/systemUser");
systemUser();